### ISSUE TITLE
Multiple layers of brackets don't work correctly

### ISSUE THREAD

**Issue by apjones6** [TruffleMuffin/Decisions#29]
This was working at some point I believe in initial code, but it may be an error (I can see multiple layers with lots of NOTs, but nothing else, so perhaps not). Also consider ordering before or after brackets to ensure that doesn't have an effect.

Should be able to do: (A AND ((B AND C) OR D)) OR E

**Comment by TruffleMuffin** [comment]
Some bracket depth is working. However this example does not.

(True OR ((True AND False) OR False)) OR False

**Comment by TruffleMuffin** [comment]
Requires implementation of http://en.wikipedia.org/wiki/Recursive_descent_parser for ExpressionProvider
